spring.application.name=smart-rw
server.port= 5400

#Postgres configuration
spring.datasource.url=jdbc:postgresql://178.128.105.164:5432/smart_rw
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# MyBatis Configuration
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.codean.smart_rw.model
mybatis.configuration.map-underscore-to-camel-case=true

# Logging debug
logging.level.com.mybatis.rentalCar.mapper=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

# JWT Configuration
application.security.jwt.secret-key=JHG76fgh78GHJ98GHJ56fghJHG78FghJHG78gfhGHJ89DFG45HJK67FFG
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000


file.upload-dir=/rw/
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

telegram.bot.token=8334839170:AAEQyWwrWeed3_t5J1HcrvNB5JNbgAhHcyU

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Queue config
rabbitmq.queue.notifikasi=queue.notifikasi.telegram
rabbitmq.exchange=exchange.smart-rw
rabbitmq.routing-key=notifikasi.telegram
rabbitmq.queue-name=telegram
